version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/library?allowPublicKeyRetrieval=true    
    depends_on:
      - mysqldb
    
    volumes:
      - .m2:/root/.m2
      
  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 33065:3306
    networks:
      - springapimysql-net  
    environment:
      MYSQL_DATABASE: library
      # MYSQL_USER: root
      MYSQL_PASSWORD: tina123456
      MYSQL_ROOT_PASSWORD: tina123456
      #- MYSQL_ROOT_PASSWORD: tina123456
networks:
  springapimysql-net: